version: '3.8'
services:
  database:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:15.1-alpine3.17
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ${POSTGRES_VOLUME_DATA_PATH}:/var/lib/postgresql/data